all:
	gcc openmp_critical_problem.c -o openmp_critical_problem -fopenmp
	gcc openmp_critical_solution.c -o openmp_critical_solution -fopenmp
	gcc semaphore_textbook.c -o semaphore_textbook
	gcc semaphore_process_problem.c -o semaphore_process_problem
	gcc semaphore_process_solution.c -o semaphore_process_solution -lrt
	gcc semaphore_thread_problem.c -o semaphore_thread_problem -lpthread
	gcc semaphore_thread_solution.c -o semaphore_thread_solution -lpthread
