all:
	gcc openmp_critical_problem.c -o openmp_critical_problem -fopenmp -lm
	gcc openmp_critical_solution.c -o openmp_critical_solution -fopenmp -lm
	gcc semaphore_textbook.c -o semaphore_textbook -lm
	gcc semaphore_process_problem.c -o semaphore_process_problem -lm
	gcc semaphore_process_solution.c -o semaphore_process_solution -lrt -lm
	gcc semaphore_thread_problem.c -o semaphore_thread_problem -lpthread -lm
	gcc semaphore_thread_solution.c -o semaphore_thread_solution -lpthread -m
